# Generated by Django 3.0.8 on 2020-07-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200723_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='creation_date',
        ),
    ]
