# Generated by Django 3.0.8 on 2020-07-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200723_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_name',
        ),
    ]
