# Generated by Django 3.0.8 on 2020-07-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200728_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
