# Generated by Django 3.0.8 on 2020-08-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200803_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='test',
            new_name='user',
        ),
    ]
