# Generated by Django 3.0.8 on 2020-08-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200803_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_name_user', to='api.User'),
            preserve_default=False,
        ),
    ]
