# Generated by Django 3.0.8 on 2020-08-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200803_1847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user_id', 'user_name')},
        ),
    ]
