# Generated by Django 3.0.8 on 2020-08-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200803_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', to_field='user_name'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
